# Generated by Django 3.0.7 on 2020-06-22 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('accept', models.BooleanField(default=False)),
                ('title', models.CharField(default=None, max_length=250)),
                ('repo', models.CharField(default=None, max_length=250)),
                ('source_branch', models.CharField(default=None, max_length=250)),
                ('target_branch', models.CharField(default=None, max_length=250)),
                ('assign_email', models.CharField(default=None, max_length=250)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
